### ISSUE TITLE
Defining `computed: { pgConfig () {} }` Causes Unnecessary GET request for entire table

### ISSUE THREAD

**Issue by johndanek** [technowledgy/vue-postgrest#100]
In my app, I have a page where a user can create a new record, which is backed by the `records` table.

RecordNew.vue
```
import { pg } from 'vue-postgrest';

export default {
  mixins: [pg],
  data() {
    record: {}
  },
  computed: {
    pgConfig () {
      return {
        route: 'records'
      }
    }
  },
  mounted() {
    this.record = this.pg.$new(createBlankRecord());
  },
  methods: {
    async createNewRecord(value) {
      await this.record.$post({ return 'minimal' });
    }
  }
}
```

Whenever I navigate to this page (`/records/new`), the code instantly fires a GET request to the postgrest API for all of the `records` table. I am only trying to connect it so that I can perform the POST when `createNewRecord` is called. If I don't have the computer->pgConfig block, the $post( call fails with an error.

How can I prevent this unnecessary GET request on page load?

**Comment by wolfgangwalther** [comment]
The mixin is used in cases where you want to show a list of things and add to that list at the same time. That's why it works with `this.pg` as a `GenericCollection`. And that includes `GET` requests to fill the collection in the first place.

For your use-case, you don't seem to need the mixin. I suggest you just use [plugin](https://technowledgy.github.io/vue-postgrest/api/#postgrest-route):

```javascript
export default {
  data() {
    record: createBlankRecord();
  },
  methods: {
    async createNewRecord(value) {
      await this.$postgrest.ready
      await this.$postgrest.records.post({}, { return 'minimal' }, this.record);
    }
  }
}
```

**Comment by johndanek** [comment]
Great, this worked! Thanks, I didn't realize that was the primary purpose of the mixin.
